"""Stable maintained batch-facing API."""

from __future__ import annotations

from zpbs.cli.batch_cli import build_arg_parser, main
from zpbs.common import (
    FOCUS_SURF_IDS,
    clamp_normalization_radius_um,
    clamp_reference_radius_um,
    format_processed_label,
    format_tension,
    force_sort_key,
    is_focus_surface_family,
    parse_boolish,
    parse_optional_int,
    resolve_analysis_date,
    resolve_run_name,
    round_nearest_micrometer,
    round_sigfigs_array,
    sanitize_h5_name,
    uses_posterior_sign_convention,
    validate_center_weight,
    validate_sphere_reference_configuration,
    validate_zernike_method,
)
from zpbs.fit.sphere_reference import (
    SpherePrefitEntry,
    SphereReferenceFit,
    VertexTarget,
    build_sphere_reference_fit,
    fit_sphere_robust,
    fit_sphere_with_fixed_radius,
    get_sphere_prefit_entry,
    infer_surface_branch_sign,
    radial_weight_profile,
    select_vertex_target,
    sphere_reference_vertex,
)
from zpbs.io.xyz import collapse_identical_initial_inputs, load_xyz_point_cloud, parse_surface_metadata
from zpbs.models import FitArtifacts, ProcessingInput, SurfaceMetadata
from zpbs.pipeline.surface_fit import (
    build_fit_artifacts,
    precompute_best_radii,
    precompute_common_normalization_radii_by_surf_id,
    run_fit_pipeline,
    zpbs_residual_on_axis_m0_um,
)
from zpbs.reporting.batch_reports import (
    artifacts_to_summary_row,
    excel_column_name,
    radial_bin_profile,
    resolve_h5_path,
    sphere_profile_z,
    write_batch_h5,
    write_batch_zp_report,
    write_csv,
    write_json,
    write_qa_report,
    write_thumbnail_plot,
    write_xlsx,
)

__all__ = [
    "FitArtifacts",
    "FOCUS_SURF_IDS",
    "ProcessingInput",
    "SpherePrefitEntry",
    "SphereReferenceFit",
    "SurfaceMetadata",
    "VertexTarget",
    "artifacts_to_summary_row",
    "build_arg_parser",
    "build_fit_artifacts",
    "build_sphere_reference_fit",
    "clamp_normalization_radius_um",
    "clamp_reference_radius_um",
    "collapse_identical_initial_inputs",
    "excel_column_name",
    "fit_sphere_robust",
    "fit_sphere_with_fixed_radius",
    "force_sort_key",
    "format_processed_label",
    "format_tension",
    "get_sphere_prefit_entry",
    "infer_surface_branch_sign",
    "is_focus_surface_family",
    "load_xyz_point_cloud",
    "main",
    "parse_boolish",
    "parse_optional_int",
    "parse_surface_metadata",
    "precompute_best_radii",
    "precompute_common_normalization_radii_by_surf_id",
    "radial_bin_profile",
    "radial_weight_profile",
    "resolve_analysis_date",
    "resolve_h5_path",
    "resolve_run_name",
    "round_nearest_micrometer",
    "round_sigfigs_array",
    "run_fit_pipeline",
    "sanitize_h5_name",
    "select_vertex_target",
    "sphere_profile_z",
    "sphere_reference_vertex",
    "zpbs_residual_on_axis_m0_um",
    "uses_posterior_sign_convention",
    "validate_center_weight",
    "validate_sphere_reference_configuration",
    "validate_zernike_method",
    "write_batch_h5",
    "write_batch_zp_report",
    "write_csv",
    "write_json",
    "write_qa_report",
    "write_thumbnail_plot",
    "write_xlsx",
]
